### ISSUE TITLE
Interested in building UCL booking website 

### ISSUE THREAD

**Issue by adamfaliq42** [uclapi/ideas#1]
I'm interested to build "Improve room bookings website" project. Is the project still going? If yes, how do I submit it upon completion?

**Comment by ChristopherHammond13** [comment]
Hey! I believe there is an attempt to build one: http://gavrilov.co.uk/room-bookings/

I have no idea what his progress is, whether it is complete, etc. If you want to build a better version feel free :)

Once you're happy with it just make a PR on this repo showing it's done and we can merge it. Good luck!
